version: "3.1"
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: mysql:inbound # イメージの名前
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password   #コンテナ内のMySQLを起動する際のパスワードを設定
        MYSQL_DATABASE: world